In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('D:\\EduNet\\NSTI_Indore25_26\\ML\\Datasets\\city_day.csv')
df

,City,Date,PM2.5,PM10,NO,NO2,NOx,NH3,CO,SO2,O3,Benzene,Toluene,Xylene,AQI,AQI_Bucket
0,Ahmedabad,2015-01-01,NaN,NaN,0.92,18.22,17.15,NaN,0.92,27.64,133.36,0.00,0.02,0.00,NaN,NaN
1,Ahmedabad,2015-01-02,NaN,NaN,0.97,15.69,16.46,NaN,0.97,24.55,34.06,3.68,5.50,3.77,NaN,NaN
2,Ahmedabad,2015-01-03,NaN,NaN,17.40,19.30,29.70,NaN,17.40,29.07,30.70,6.80,16.40,2.25,NaN,NaN
3,Ahmedabad,2015-01-04,NaN,NaN,1.70,18.48,17.97,NaN,1.70,18.59,36.08,4.43,10.14,1.00,NaN,NaN
4,Ahmedabad,2015-01-05,NaN,NaN,22.10,21.42,37.76,NaN,22.10,39.33,39.31,7.01,18.89,2.78,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29526,Visakhapatnam,2020-06-27,15.02,50.94,7.68,25.06,19.54,12.47,0.47,8.55,23.30,2.24,12.07,0.73,41.0,Good
29527,Visakhapatnam,2020-06-28,24.38,74.09,3.42,26.06,16.53,11.99,0.52,12.72,30.14,0.74,2.21,0.38,70.0,Satisfactory
29528,Visakhapatnam,2020-06-29,22.91,65.73,3.45,29.53,18.33,10.71,0.48,8.42,30.96,0.01,0.01,0.00,68.0,Satisfactory
29529,Visakhapatnam,2020-06-30,16.64,49.97,4.05,29.26,18.80,10.03,0.52,9.84,28.30,0.00,0.00,0.00,54.0,Satisfactory
29530,Visakhapatnam,2020-07-01,15.00,66.00,0.40,26.85,14.05,5.20,0.59,2.10,17.05,NaN,NaN,NaN,50.0,Good

In [3]:
df.isna().sum()

City              0
Date              0
PM2.5          4598
PM10          11140
NO             3582
NO2            3585
NOx            4185
NH3           10328
CO             2059
SO2            3854
O3             4022
Benzene        5623
Toluene        8041
Xylene        18109
AQI            4681
AQI_Bucket     4681
dtype: int64

In [4]:
df.columns

Index(['City', 'Date', 'PM2.5', 'PM10', 'NO', 'NO2', 'NOx', 'NH3', 'CO', 'SO2',
       'O3', 'Benzene', 'Toluene', 'Xylene', 'AQI', 'AQI_Bucket'],
      dtype='object')

In [5]:
df = df[['PM2.5', 'PM10', 'NO2', 'NH3', 'CO', 'SO2','O3','AQI']]

In [6]:
df.isna().sum()

PM2.5     4598
PM10     11140
NO2       3585
NH3      10328
CO        2059
SO2       3854
O3        4022
AQI       4681
dtype: int64

In [7]:
sample = df

In [8]:
sample = sample[(sample['AQI'].isna() == False)]
sample

        PM2.5   PM10    NO2    NH3     CO    SO2      O3    AQI
28      83.13    NaN  28.71    NaN   6.93  49.52   59.76  209.0
29      79.84    NaN  28.68    NaN  13.85  48.49   97.07  328.0
30      94.52    NaN  32.66    NaN  24.39  67.39  111.33  514.0
31     135.99    NaN  42.08    NaN  43.48  75.23  102.70  782.0
32     178.33    NaN  35.31    NaN  54.56  55.04  107.38  914.0
...       ...    ...    ...    ...    ...    ...     ...    ...
29526   15.02  50.94  25.06  12.47   0.47   8.55   23.30   41.0
29527   24.38  74.09  26.06  11.99   0.52  12.72   30.14   70.0
29528   22.91  65.73  29.53  10.71   0.48   8.42   30.96   68.0
29529   16.64  49.97  29.26  10.03   0.52   9.84   28.30   54.0
29530   15.00  66.00  26.85   5.20   0.59   2.10   17.05   50.0

[24850 rows x 8 columns]

In [9]:
sample.isna().sum()

PM2.5     678
PM10     7086
NO2       391
NH3      6536
CO        445
SO2       605
O3        807
AQI         0
dtype: int64

In [10]:
sample['PM2.5'].fillna(round(sample['PM2.5'].mean(),2),inplace=True)
sample['NO2'].fillna(round(sample['NO2'].mean(),2),inplace=True)
sample['CO'].fillna(round(sample['CO'].mean(),2),inplace=True)
sample['SO2'].fillna(round(sample['SO2'].mean(),2),inplace=True)
sample['O3'].fillna(round(sample['O3'].mean(),2),inplace=True)

C:\Users\Jash\AppData\Local\Temp\ipykernel_27264\2762596402.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  sample['PM2.5'].fillna(round(sample['PM2.5'].mean(),2),inplace=True)
C:\Users\Jash\AppData\Local\Temp\ipykernel_27264\2762596402.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  sample['PM2.5'].fillna(round(sample['PM2.5'].mean(),2),inplace=True)
C:\Users\Jash\AppData\Local\Temp\ipykernel_27264\2762596402.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  sample['NO2'].fillna(round(sample['NO2'].mean(),2),inplace=True)
C:\Users\Jash\AppData\Local\Temp\ipykernel_27264\2762596402.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  sample['NO2'].fillna(round(sample['NO2'].mean(),2),inplace=True)
C:\Users\Jash\AppData\Local\Temp\ipykernel_27264\2762596402.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  sample['CO'].fillna(round(sample['CO'].mean(),2),inplace=True)
C:\Users\Jash\AppData\Local\Temp\ipykernel_27264\2762596402.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  sample['CO'].fillna(round(sample['CO'].mean(),2),inplace=True)
C:\Users\Jash\AppData\Local\Temp\ipykernel_27264\2762596402.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  sample['SO2'].fillna(round(sample['SO2'].mean(),2),inplace=True)
C:\Users\Jash\AppData\Local\Temp\ipykernel_27264\2762596402.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  sample['SO2'].fillna(round(sample['SO2'].mean(),2),inplace=True)
C:\Users\Jash\AppData\Local\Temp\ipykernel_27264\2762596402.py:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  sample['O3'].fillna(round(sample['O3'].mean(),2),inplace=True)
C:\Users\Jash\AppData\Local\Temp\ipykernel_27264\2762596402.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  sample['O3'].fillna(round(sample['O3'].mean(),2),inplace=True)

In [11]:
sample.isna().sum()

PM2.5       0
PM10     7086
NO2         0
NH3      6536
CO          0
SO2         0
O3          0
AQI         0
dtype: int64

# PM10

In [12]:
forPM10 = sample[['PM2.5','NO2','SO2','CO','O3','AQI','PM10']]
forPM10

        PM2.5    NO2    SO2     CO      O3    AQI   PM10
28      83.13  28.71  49.52   6.93   59.76  209.0    NaN
29      79.84  28.68  48.49  13.85   97.07  328.0    NaN
30      94.52  32.66  67.39  24.39  111.33  514.0    NaN
31     135.99  42.08  75.23  43.48  102.70  782.0    NaN
32     178.33  35.31  55.04  54.56  107.38  914.0    NaN
...       ...    ...    ...    ...     ...    ...    ...
29526   15.02  25.06   8.55   0.47   23.30   41.0  50.94
29527   24.38  26.06  12.72   0.52   30.14   70.0  74.09
29528   22.91  29.53   8.42   0.48   30.96   68.0  65.73
29529   16.64  29.26   9.84   0.52   28.30   54.0  49.97
29530   15.00  26.85   2.10   0.59   17.05   50.0  66.00

[24850 rows x 7 columns]

In [13]:
forPM10.dropna(inplace=True)
forPM10.isna().sum()

C:\Users\Jash\AppData\Local\Temp\ipykernel_27264\1383463457.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  forPM10.dropna(inplace=True)

PM2.5    0
NO2      0
SO2      0
CO       0
O3       0
AQI      0
PM10     0
dtype: int64

In [14]:
# forPM10.c

In [15]:
X = forPM10.drop(['PM10'],axis = 1)
y = forPM10['PM10']

In [16]:
X

       PM2.5    NO2     SO2     CO     O3    AQI
1595   37.55  85.12  163.01  15.08  48.23  281.0
1596   33.97  79.71   91.26  14.67  51.86  330.0
1597   35.48  77.61   98.35  18.02  38.99  356.0
1598   34.11  75.23   88.66  13.27  42.22  359.0
1599   33.69  68.90   80.90  34.56  36.95  547.0
...      ...    ...     ...    ...    ...    ...
29526  15.02  25.06    8.55   0.47  23.30   41.0
29527  24.38  26.06   12.72   0.52  30.14   70.0
29528  22.91  29.53    8.42   0.48  30.96   68.0
29529  16.64  29.26    9.84   0.52  28.30   54.0
29530  15.00  26.85    2.10   0.59  17.05   50.0

[17764 rows x 6 columns]

In [17]:
y

1595     122.41
1596     116.32
1597     130.07
1598     138.31
1599     111.73
          ...
29526     50.94
29527     74.09
29528     65.73
29529     49.97
29530     66.00
Name: PM10, Length: 17764, dtype: float64

In [18]:
from sklearn.linear_model import LinearRegression

In [19]:
PM10Model = LinearRegression()

In [20]:
PM10Model.fit(X,y)

LinearRegression()

In [21]:
def predPM10(PM2_5, NO2, SO2, CO, O3, AQI):
    result = PM10Model.predict([[PM2_5, NO2, SO2,	CO, O3, AQI]])
    return result[0]

In [22]:
# sample[sample['PM10'].isna()]['PM10'] = sample[
#     sample['PM10'].isna()
# ].apply(
#     predPM10(
#         sample['PM2.5'],
#         sample['NO2'],
#         sample['SO2'],
#         sample['CO'],
#         sample['O3'],
#         sample['AQI'],
#     )
# )

In [23]:
df

       PM2.5   PM10    NO2    NH3     CO    SO2      O3   AQI
0        NaN    NaN  18.22    NaN   0.92  27.64  133.36   NaN
1        NaN    NaN  15.69    NaN   0.97  24.55   34.06   NaN
2        NaN    NaN  19.30    NaN  17.40  29.07   30.70   NaN
3        NaN    NaN  18.48    NaN   1.70  18.59   36.08   NaN
4        NaN    NaN  21.42    NaN  22.10  39.33   39.31   NaN
...      ...    ...    ...    ...    ...    ...     ...   ...
29526  15.02  50.94  25.06  12.47   0.47   8.55   23.30  41.0
29527  24.38  74.09  26.06  11.99   0.52  12.72   30.14  70.0
29528  22.91  65.73  29.53  10.71   0.48   8.42   30.96  68.0
29529  16.64  49.97  29.26  10.03   0.52   9.84   28.30  54.0
29530  15.00  66.00  26.85   5.20   0.59   2.10   17.05  50.0

[29531 rows x 8 columns]

In [24]:
df = df.dropna()

In [25]:
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score

# ==============================
# Step 2: Basic Cleaning
# ==============================

# Drop non-useful columns
df = df.drop(columns=['City'], errors='ignore')

# Convert Date (optional)
if 'Date' in df.columns:
    df['Date'] = pd.to_datetime(df['Date'], errors='coerce')
    df['Date'] = df['Date'].map(pd.Timestamp.toordinal)

# ==============================
# Step 3: Drop Missing Values
# ==============================

df = df.dropna()

print("Shape After Dropping NA:", df.shape)

# ==============================
# Step 4: Features & Target
# ==============================

if 'AQI' not in df.columns:
    raise ValueError("AQI column not found!")

X = df.drop(columns=['AQI'])
y = df['AQI']

# ==============================
# Step 5: Train-Test Split
# ==============================

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# ==============================
# Step 6: Train Model
# ==============================

model = LinearRegression()
model.fit(X_train, y_train)

# ==============================
# Step 7: Prediction
# ==============================

y_pred = model.predict(X_test)

# ==============================
# Step 8: Evaluation
# ==============================

rmse = np.sqrt(mean_squared_error(y_test, y_pred))
r2 = r2_score(y_test, y_pred)

print("\nModel Performance:")
print("RMSE:", rmse)
print("R2 Score:", r2)

Shape After Dropping NA: (14402, 8)

Model Performance:
RMSE: 28.633596122244256
R2 Score: 0.9000379560906517