In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('D:\\EduNet\\NSTI_Indore25_26\\ML\\Datasets\\Customer Segmentation\\train.csv')
df

,ID,Gender,Ever_Married,Age,Graduated,Profession,Work_Experience,Spending_Score,Family_Size,Var_1,Segmentation
0,462809,Male,No,22,No,Healthcare,1.0,Low,4.0,Cat_4,D
1,462643,Female,Yes,38,Yes,Engineer,NaN,Average,3.0,Cat_4,A
2,466315,Female,Yes,67,Yes,Engineer,1.0,Low,1.0,Cat_6,B
3,461735,Male,Yes,67,Yes,Lawyer,0.0,High,2.0,Cat_6,B
4,462669,Female,Yes,40,Yes,Entertainment,NaN,High,6.0,Cat_6,A
...,...,...,...,...,...,...,...,...,...,...,...
8063,464018,Male,No,22,No,NaN,0.0,Low,7.0,Cat_1,D
8064,464685,Male,No,35,No,Executive,3.0,Low,4.0,Cat_4,D
8065,465406,Female,No,33,Yes,Healthcare,1.0,Low,1.0,Cat_6,D
8066,467299,Female,No,27,Yes,Healthcare,1.0,Low,4.0,Cat_6,B
8067,461879,Male,Yes,37,Yes,Executive,0.0,Average,3.0,Cat_4,B

In [3]:
df.isna().sum()

ID                   0
Gender               0
Ever_Married       140
Age                  0
Graduated           78
Profession         124
Work_Experience    829
Spending_Score       0
Family_Size        335
Var_1               76
Segmentation         0
dtype: int64

In [4]:
df['Ever_Married'].mode()

0    Yes
Name: Ever_Married, dtype: object

In [5]:
df['Ever_Married'].fillna('Yes',inplace=True)
df.isna().sum()

C:\Users\Jash\AppData\Local\Temp\ipykernel_20808\2830144055.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Ever_Married'].fillna('Yes',inplace=True)

ID                   0
Gender               0
Ever_Married         0
Age                  0
Graduated           78
Profession         124
Work_Experience    829
Spending_Score       0
Family_Size        335
Var_1               76
Segmentation         0
dtype: int64

In [6]:
df['Graduated'].mode()

0    Yes
Name: Graduated, dtype: object

In [7]:
df['Graduated'].fillna('Yes',inplace=True)
df.isna().sum()

C:\Users\Jash\AppData\Local\Temp\ipykernel_20808\1241272823.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Graduated'].fillna('Yes',inplace=True)

ID                   0
Gender               0
Ever_Married         0
Age                  0
Graduated            0
Profession         124
Work_Experience    829
Spending_Score       0
Family_Size        335
Var_1               76
Segmentation         0
dtype: int64

In [8]:
df['Profession'].mode()

0    Artist
Name: Profession, dtype: object

In [9]:
df['Profession'].fillna(
    'Artist',inplace=True)
df.isna().sum()

C:\Users\Jash\AppData\Local\Temp\ipykernel_20808\2910468756.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Profession'].fillna(

ID                   0
Gender               0
Ever_Married         0
Age                  0
Graduated            0
Profession           0
Work_Experience    829
Spending_Score       0
Family_Size        335
Var_1               76
Segmentation         0
dtype: int64

In [10]:
df['Work_Experience'].mean()

2.641663213150988

In [11]:
df['Work_Experience'].fillna(2.6,inplace=True)
df.isna().sum()

C:\Users\Jash\AppData\Local\Temp\ipykernel_20808\1991451329.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Work_Experience'].fillna(2.6,inplace=True)

ID                   0
Gender               0
Ever_Married         0
Age                  0
Graduated            0
Profession           0
Work_Experience      0
Spending_Score       0
Family_Size        335
Var_1               76
Segmentation         0
dtype: int64

In [12]:
df['Family_Size'].fillna(df['Family_Size'].mean(),inplace=True)
df.isna().sum()

C:\Users\Jash\AppData\Local\Temp\ipykernel_20808\285654246.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Family_Size'].fillna(df['Family_Size'].mean(),inplace=True)

ID                  0
Gender              0
Ever_Married        0
Age                 0
Graduated           0
Profession          0
Work_Experience     0
Spending_Score      0
Family_Size         0
Var_1              76
Segmentation        0
dtype: int64

In [13]:
df = df.drop(['ID','Var_1'],axis=1)
df

,Gender,Ever_Married,Age,Graduated,Profession,Work_Experience,Spending_Score,Family_Size,Segmentation
0,Male,No,22,No,Healthcare,1.0,Low,4.0,D
1,Female,Yes,38,Yes,Engineer,2.6,Average,3.0,A
2,Female,Yes,67,Yes,Engineer,1.0,Low,1.0,B
3,Male,Yes,67,Yes,Lawyer,0.0,High,2.0,B
4,Female,Yes,40,Yes,Entertainment,2.6,High,6.0,A
...,...,...,...,...,...,...,...,...,...
8063,Male,No,22,No,Artist,0.0,Low,7.0,D
8064,Male,No,35,No,Executive,3.0,Low,4.0,D
8065,Female,No,33,Yes,Healthcare,1.0,Low,1.0,D
8066,Female,No,27,Yes,Healthcare,1.0,Low,4.0,B
8067,Male,Yes,37,Yes,Executive,0.0,Average,3.0,B

In [14]:
print(df['Gender'].unique())
print(df['Ever_Married'].unique())
print(df['Graduated'].unique())
print(df['Profession'].unique())
print(df['Spending_Score'].unique())
print(df['Segmentation'].unique())

['Male' 'Female']
['No' 'Yes']
['No' 'Yes']
['Healthcare' 'Engineer' 'Lawyer' 'Entertainment' 'Artist' 'Executive'
 'Doctor' 'Homemaker' 'Marketing']
['Low' 'Average' 'High']
['D' 'A' 'B' 'C']

In [ ]:
df['Gender'] = df['Gender'].replace(
    {'Male':1,
     'Female':0}
    )

C:\Users\Jash\AppData\Local\Temp\ipykernel_20808\2087688777.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['Gender'] = df['Gender'].replace({'Male':1,'Female':0})

In [17]:
df['Ever_Married'] = df['Ever_Married'].replace({
    'Yes':1,
    'No':0
})
df

C:\Users\Jash\AppData\Local\Temp\ipykernel_20808\3457465708.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['Ever_Married'] = df['Ever_Married'].replace({

,Gender,Ever_Married,Age,Graduated,Profession,Work_Experience,Spending_Score,Family_Size,Segmentation
0,1,0,22,No,Healthcare,1.0,Low,4.0,D
1,0,1,38,Yes,Engineer,2.6,Average,3.0,A
2,0,1,67,Yes,Engineer,1.0,Low,1.0,B
3,1,1,67,Yes,Lawyer,0.0,High,2.0,B
4,0,1,40,Yes,Entertainment,2.6,High,6.0,A
...,...,...,...,...,...,...,...,...,...
8063,1,0,22,No,Artist,0.0,Low,7.0,D
8064,1,0,35,No,Executive,3.0,Low,4.0,D
8065,0,0,33,Yes,Healthcare,1.0,Low,1.0,D
8066,0,0,27,Yes,Healthcare,1.0,Low,4.0,B
8067,1,1,37,Yes,Executive,0.0,Average,3.0,B